### ISSUE TITLE
Images have a lot of layout shift

### ISSUE THREAD

**Issue by westonruter** [wptavern/the-tavern#2]
I'm noticing images have a lot of layout shift going on, for example on [this post](https://wptavern.com/skins-are-back-in-style-proposal-for-themes-to-bundle-user-selectable-design-variations):

https://user-images.githubusercontent.com/134745/142078687-e0a8581c-aac1-4eb0-bdba-cfab56c7825d.mov

And also on the homepage:

https://user-images.githubusercontent.com/134745/142079189-282b084b-391c-4ae8-983c-b486031a58b5.mov

I've throttled the network connection to Fast 3G in Chrome DevTools.

I haven't identified the specific cause, but it seems Jetpack's Lazy Loading may be involved, at least in part.

**Comment by westonruter** [comment]
Huh, when JavaScript is turned off, the images on the homepage fail to load entirely:

![image](https://user-images.githubusercontent.com/134745/142080949-a8193040-c175-4240-afe1-3984efac5886.png)

But on a singular post, there is no layout shift present.

**Comment by westonruter** [comment]
Possible issue in Jetpack: https://github.com/Automattic/jetpack/issues/16421

**Comment by westonruter** [comment]
Possibly related: https://github.com/WordPress/gutenberg/pull/36552

**Comment by justintadlock** [comment]
That's weird.  We're using the Jetpack Lazyload.

**Comment by westonruter** [comment]
Maybe try deactivating it since the [majority](https://caniuse.com/loading-lazy-attr) of browsers support lazy-load now by default?

**Comment by westonruter** [comment]
Layout shift has been eliminated with the new design: https://wptavern.com/wp-tavern-is-sporting-a-new-website-design
